### ISSUE TITLE
Stuck PrEnergy* counters

### ISSUE THREAD

**Issue by blanosko** [blanosko/gas-meter-ha#2]
hello, my counters are stuck on the same value all the time, could someone tell me as a complete amateur how to fix it?

_Originally posted by @Pelikanoooo in https://github.com/blanosko/gas-meter-ha/issues/1#issuecomment-1905914732_

**Comment by blanosko** [comment]
Please refer to the README.md:

https://github.com/blanosko/gas-meter-ha#zeroing-energy-counters-of-your-boiler

**Comment by Pelikanoooo** [comment]
great, could you advise me where to enter the reset command?

**Comment by blanosko** [comment]
It's stated in the referenced README.md chapter:
> You can do this by writing zeros to the registers with these commands from the EBUSD VM/container:

**Comment by Pelikanoooo** [comment]
unfortunately, even after reading it, I don't know where to enter the command, I'm a complete amateur, please help

**Comment by blanosko** [comment]
Do you satisfy all prerequisities stated in README.md?

**Comment by Pelikanoooo** [comment]
Please advise me where to enter the command so that I can have peace of mind, I don't care anymore, I don't want to bother you, I just don't know who to turn to, I probably started ebusd by accident :-D and when my computer stopped working, Google threw out your thread about reset.

**Comment by blanosko** [comment]
I would really like to help you set this up, but if you don't even know if you are running ebusd and can't answer the question about prerequisities, then I don't know how to help you.

Furthermore, based on your last reply, I'm not even sure if you intend to estimate gas meter usage with a script from this repository. Please note that this is not a forum; it's an issue tracking board specific to the code in this repository. The README.md is tailored to the code in this repository and is not an implementation guide for ebusd.

Please clearly state what you want to accomplish. If you need assistance with setting up ebusd, refer to the documentation in John30's repository at:

[https://github.com/john30/ebusd](https://github.com/john30/ebusd)

**Comment by Pelikanoooo** [comment]
I know this is not a forum, I run ebusd from john30. I don't use your script, but you describe the problem I have, so I need to write step by step where to enter the command to reset the counter....
![Snímek obrazovky 2024-01-23 155603](https://github.com/blanosko/gas-meter-ha/assets/25460751/ef56cdf9-cdb2-40c3-a08c-12ed58157d61)

**Comment by blanosko** [comment]
It's off-topic then but I will try to help you. So you have everything set up and you just need to reset the counters so they increase again. Now, please tell me how you are running ebusd. Do you have it as standalone VM or in docker/LXC container or as addon in Home Assistant?

I'm asking because you will need to access CLI of the ebusd VM/container/addon and issue the write commands from there. But I need that information so I can better navigate you where to do that if you don't know how.

**Comment by Pelikanoooo** [comment]
yes, everything is up and running, you only need to reset the counter, I have ebusd installed as an add-on in Home Assistant on the RPi3, thank you very much :)

**Comment by blanosko** [comment]
In your case it is not possible to directly access CLI of addon containers. But, you could simply publish payload 0 to the ebusd/bai/PrEnergySumHc1/set topic (assuming that bai is your circuit name) and wait if the value actually changes. You should even see it in ebusd addons Logs pages.

If the write is successful, repeat the publish step for all of the counters.

**Comment by Pelikanoooo** [comment]
if I send the pre-publish command in HA, there is no overwriting to 0
![Snímek obrazovky 2024-01-23 172746](https://github.com/blanosko/gas-meter-ha/assets/25460751/88a7b520-3c7a-4613-ae44-2e6aa4dc0e33)
![Snímek obrazovky 2024-01-23 172852](https://github.com/blanosko/gas-meter-ha/assets/25460751/969a4b0c-15c1-4b69-95d0-0bef62e1c745)

**Comment by blanosko** [comment]
I'm certain that the problem is that you are using default ebusd configuration CSV files and the PrEnergy* counters are set to read-only. You need to refer to this part of documentation for ebusd addon:

> Custom CSV or MQTT cfg files:
To use custom config files you can use the configpath option. You can create a local copy of https://github.com/john30/ebusd-configuration in your "/config" folder and change configpath to e.g. "/config/ebusd-configuration/latest/en". Custom CSV files must be in the /config folder.

Then change the config of addon and add this option:

```
configpath: /config/ebusd-configuration/latest/en
```

After that change the lines that has PrEnergy* entries of loaded CSV configuration*** file to:

```
r1;w,,PrEnergySumHwc1,PrEnergySumDHW1_DK,,,,"C500",,,ULG,,,Predictive Maintenance data
r1;w,,PrEnergyCountHwc1,PrEnergyCountDHW1_DK,,,,"C600",,,ULG,,,Predictive Maintenance data
r1;w,,PrEnergySumHc1,PrEnergySumCH1_DK,,,,"F500",,,ULG,,,Predictive Maintenance data
r1;w,,PrEnergyCountHc1,PrEnergyCountCH1_DK,,,,"F600",,,ULG,,,Predictive Maintenance data
```

After these step, reload ebusd addon and it should be possible to write to that register.

***You can find which CSV file got loaded when bus scan has finished when you look to the logs of the ebusd addon. You can paste it here so I can look at that also.

**Comment by Pelikanoooo** [comment]
that's all great, I've been trying all afternoon to do what you write and I haven't succeeded at all....is there any way to let you do it remotely via TeamViewer?
